# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-14 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productfeatured_make_image_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatured',
            name='text_css_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
